general:
  enable_channels: [0,1,2]
  dut_channel: 0
  clock_channel: 1
  store_waveform: false
  winsize: 3.0e-6
  peak_finding_threshold: 1.0

capacitor_param:
  time_start: 1500 
  time_win: 700
  cycle_size: 1300
  ncycles: 25


